#Dockerfile Backend

FROM node:10.15.1

WORKDIR /app
# COPY package.json /app
# RUN npm install
RUN npm install -g nodemon --quiet
# COPY ./Back .
EXPOSE 3000
# CMD ["npm", "start"]


# docker build -t nameimage .